import type { WheelConfig, RingConfig } from 'pixi-wheels';

const j = (v: unknown): string => JSON.stringify(v);

function ringCalls(r: RingConfig, indent: string): string[] {
  const out: string[] = [];
  out.push(`${indent}.radius(${r.outerRadius}, ${r.innerRadius ?? 0})`);
  if (r.startAngle !== undefined && r.startAngle !== -90) out.push(`${indent}.startAngle(${r.startAngle})`);
  if (r.direction) out.push(`${indent}.direction(${j(r.direction)})`);
  if (r.palette) out.push(`${indent}.palette(${j(r.palette)})`);
  out.push(`${indent}.sections(${JSON.stringify(r.sections, null, 2).split('\n').join(`\n${indent}`)})`);
  for (const p of r.pointers ?? []) out.push(`${indent}.pointer(${j(p)})`);
  if (r.skin) out.push(`${indent}.skin(${j(r.skin)})`);
  if (r.dynamic) out.push(`${indent}.dynamic(${JSON.stringify(r.dynamic, null, 2).split('\n').join(`\n${indent}`)})`);
  return out;
}

/**
 * The fluent code a config stands for. What the studio's Code tab shows and
 * what the exported example project runs. Runs as a recipe: `app` (and
 * `assets` when textures are referenced) are in scope.
 */
export function configToCode(cfg: WheelConfig, opts: { withAssets?: boolean } = {}): string {
  const main = cfg.rings.find((r) => r.id === 'main') ?? cfg.rings[0];
  const lines: string[] = [];
  lines.push('// @ts-nocheck');
  lines.push('// Generated by the pixi-wheels studio. Edit freely; the Code tab runs this.');
  lines.push('// Injected globals: WheelBuilder, SpinPresets, app' + (opts.withAssets ? ', assets' : ''));
  lines.push('');
  lines.push('const wheel = new WheelBuilder()');
  if (cfg.name) lines.push(`  .name(${j(cfg.name)})`);
  if (cfg.direction && cfg.direction !== 'cw') lines.push(`  .direction(${j(cfg.direction)})`);
  lines.push(...ringCalls(main, '  '));
  for (const r of cfg.rings) {
    if (r === main) continue;
    lines.push(`  .ring(${j(r.id)}, (r) => r`);
    lines.push(...ringCalls(r, '    '));
    lines.push('  )');
  }
  for (const [name, profile] of Object.entries(cfg.speeds ?? {})) lines.push(`  .speed(${j(name)}, ${j(profile)})`);
  if (cfg.initialSpeed) lines.push(`  .initialSpeed(${j(cfg.initialSpeed)})`);
  if (cfg.landing && Object.keys(cfg.landing).length > 0) lines.push(`  .landing(${j(cfg.landing)})`);
  if (cfg.skip && Object.keys(cfg.skip).length > 0) lines.push(`  .skip(${j(cfg.skip)})`);
  if (cfg.idle) lines.push(`  .idle(${j(cfg.idle)})`);
  if (cfg.adapter) lines.push(`  .adapter(${j(cfg.adapter)})`);
  if (opts.withAssets) lines.push('  .assets(assets)');
  lines.push('  .ticker(app.ticker)');
  lines.push('  .build();');
  lines.push('');
  lines.push('return {');
  lines.push('  wheel,');
  lines.push('  onSpin: async () => {');
  lines.push('    const spin = wheel.spin();');
  lines.push('    await new Promise((r) => setTimeout(r, 300)); // your server call goes here');
  lines.push('    wheel.setResult({ index: Math.floor(Math.random() * wheel.sections.length) });');
  lines.push('    await spin;');
  lines.push('  },');
  lines.push('};');
  return lines.join('\n');
}

/** True when any skin in the config references an asset key. */
export function configUsesAssets(cfg: WheelConfig): boolean {
  return cfg.rings.some((r) => (r.skin && r.skin.type !== 'graphics' && r.skin.type !== 'debug') || (r.pointers ?? []).some((p) => p.skin && p.skin.type === 'texture'));
}

/** The files of a runnable Vite project around a config. Asset files are added by the caller. */
export function exampleProjectFiles(cfg: WheelConfig, assetKeys: string[], version: string): Record<string, string> {
  const files: Record<string, string> = {};
  files['package.json'] = JSON.stringify(
    {
      name: (cfg.name ?? 'my-wheel').toLowerCase().replace(/[^a-z0-9-]+/g, '-'),
      private: true,
      type: 'module',
      scripts: { dev: 'vite', build: 'vite build', preview: 'vite preview' },
      dependencies: { 'pixi-wheels': `^${version}`, 'pixi.js': '^8.18.1', ...(assetKeys.some((k) => /\.(json|atlas|skel)$/.test(k)) ? { '@esotericsoftware/spine-pixi-v8': '~4.2.110' } : {}) },
      devDependencies: { typescript: '^5.6.0', vite: '^6.0.0' },
    },
    null,
    2,
  );
  files['index.html'] = `<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <title>${cfg.name ?? 'pixi-wheels'}</title>
    <style>html,body{margin:0;height:100%;background:#0b0d12;color:#fff;font-family:system-ui,sans-serif}#ui{position:fixed;left:16px;bottom:16px;display:flex;gap:8px}button{padding:10px 16px;border-radius:8px;border:1px solid #444;background:#1c1f28;color:#fff;cursor:pointer}</style>
  </head>
  <body>
    <div id="ui"><button id="spin">Spin</button><button id="skip">Skip</button></div>
    <script type="module" src="/src/main.ts"></script>
  </body>
</html>
`;
  files['src/main.ts'] = `import { Application, Assets, type Texture } from 'pixi.js';
import { WheelBuilder, enableDebug, type WheelConfig, type AssetResolver } from 'pixi-wheels';
${assetKeys.some((k) => /\.(json|atlas|skel)$/.test(k)) ? "import 'pixi-wheels/spine';\nimport '@esotericsoftware/spine-pixi-v8';\n" : ''}
const app = new Application();
await app.init({ resizeTo: window, background: '#0b0d12', antialias: true });
document.body.appendChild(app.canvas);

const config: WheelConfig = await (await fetch('/wheel.config.json')).json();

// Every asset the config references, loaded by its key from /assets/.
const ASSET_KEYS = ${JSON.stringify(assetKeys)};
const textures: Record<string, Texture> = {};
for (const key of ASSET_KEYS) {
  if (/\\.(png|webp|jpe?g|avif)$/i.test(key)) textures[key] = await Assets.load<Texture>(\`/assets/\${key}\`);
  else Assets.add({ alias: key, src: \`/assets/\${key}\` });
}
${assetKeys.some((k) => /\.(json|atlas|skel)$/.test(k)) ? "await Assets.load(ASSET_KEYS.filter((k) => /\\.(json|atlas|skel)$/i.test(k)));\n" : ''}
const assets: AssetResolver = {
  texture(key) {
    const t = textures[key];
    if (!t) throw new Error(\`Missing texture \${key}\`);
    return t;
  },
};

const wheel = WheelBuilder.fromConfig(config, { assets }).ticker(app.ticker).build();
wheel.position.set(app.screen.width / 2, app.screen.height / 2);
app.stage.addChild(wheel);
app.renderer.on('resize', () => wheel.position.set(app.screen.width / 2, app.screen.height / 2));
enableDebug(wheel);

wheel.events.on('spin:landing', ({ section }) => console.log('landed on', section.id, section.value));
wheel.events.on('pointer:tick', ({ speed }) => { /* play a click, scaled by speed */ void speed; });

document.getElementById('spin')!.addEventListener('click', async () => {
  if (wheel.isSpinning) return;
  const spin = wheel.spin();
  // Replace with your server call. The adapter in the config says how to read it:
  // const target = createTargetAdapter(config.adapter!)(await api.spinWheel());
  await new Promise((r) => setTimeout(r, 400));
  wheel.setResult({ index: Math.floor(Math.random() * wheel.sections.length) });
  await spin;
});
document.getElementById('skip')!.addEventListener('click', () => {
  try { wheel.skip(); } catch { wheel.requestSkip(); }
});
`;
  files['public/wheel.config.json'] = JSON.stringify(cfg, null, 2);
  files['README.md'] = `# ${cfg.name ?? 'My wheel'}

Exported from the pixi-wheels studio.

\`\`\`bash
npm install
npm run dev
\`\`\`

- \`public/wheel.config.json\` is the wheel. Edit it, or load it back into the studio.
- \`public/assets/\` holds the textures and Spine files the skins reference by file name.
- \`src/main.ts\` builds the wheel with \`WheelBuilder.fromConfig\`, wires two buttons and logs the landing.

Studio art (if any) belongs to its studio and is not covered by the MIT licence of the engine.
`;
  files['tsconfig.json'] = JSON.stringify({ compilerOptions: { target: 'ES2022', module: 'ESNext', moduleResolution: 'bundler', strict: true, skipLibCheck: true, types: ['vite/client'] }, include: ['src'] }, null, 2);
  return files;
}
